# user table
type User @table(key: "clerkId") {
  clerkId: String! @unique
  email: String!
  username: String
  imageUrl: String
}

# skill table
type Skill @table {
  id: UUID! @default(expr: "uuidV4()")
  # relationship
  author: User!
  # skill content
  title: String!
  description: String!
  tags: [String!]!
  # Technical
  installCommand: String!
  promptConfig: String!
  usageExample: String!

  # metadata
  createdAt: Timestamp! @default(expr: "request.time")
}
